# Generated by Django 4.2.2 on 2023-07-19 10:21

import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PmsUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(default='临时用户', max_length=50, unique=True, verbose_name='用户姓名')),
                ('is_super', models.CharField(default='0', max_length=50, verbose_name='是否管理员')),
                ('usernicname', models.CharField(default=users.models.get_default, max_length=50, null=True, unique=True, verbose_name='昵称')),
                ('userjob', models.CharField(default='技术经理', max_length=50, null=True, verbose_name='岗位')),
                ('userbase', models.CharField(default='CD', max_length=50, null=True, verbose_name='地区')),
                ('userworknum', models.CharField(default=users.models.default_worknum, max_length=50, null=True, unique=True, verbose_name='工号')),
                ('useremail', models.CharField(default=users.models.default_email, max_length=50, null=True, unique=True, verbose_name='邮箱')),
                ('userphonenum', models.CharField(default=users.models.default_phone, max_length=11, null=True, unique=True, verbose_name='电话')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
                'db_table': 'pms_user_controller',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
