# Generated by Django 4.2.2 on 2023-07-19 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PmsProductsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='', max_length=50, verbose_name='产品名称')),
                ('product_version', models.CharField(default='v1.0.0', max_length=50, verbose_name='部署版本')),
                ('product_install_method', models.CharField(default='未知', max_length=50, null=True, unique=True, verbose_name='部署方式')),
                ('product_ivc', models.CharField(default='zhuiyi自研', max_length=50, null=True, verbose_name='ivc')),
                ('product_database', models.CharField(default='zhuiyi自研', max_length=50, null=True, verbose_name='数据库')),
                ('product_middleware', models.CharField(default='zhuiyi自研', max_length=50, null=True, verbose_name='中间件')),
            ],
            options={
                'verbose_name': '产品信息',
                'verbose_name_plural': '产品信息',
                'db_table': 'pms_products_list',
            },
        ),
    ]
