# Generated by Django 4.2.2 on 2023-07-19 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pmsproductslist',
            name='product_database',
        ),
        migrations.RemoveField(
            model_name='pmsproductslist',
            name='product_ivc',
        ),
        migrations.RemoveField(
            model_name='pmsproductslist',
            name='product_middleware',
        ),
        migrations.AddField(
            model_name='pmsproductslist',
            name='product_nodes',
            field=models.CharField(default='未知', max_length=50, null=True, verbose_name='产品备注'),
        ),
    ]
