# Generated by Django 4.2.2 on 2023-07-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_pmsproductslist_product_database_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pmsproductslist',
            name='product_nodes',
            field=models.CharField(default='无', max_length=50, null=True, verbose_name='产品备注'),
        ),
    ]
