# Generated by Django 4.2.2 on 2023-09-12 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operationHistory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pmsoperationlogs',
            name='user',
            field=models.CharField(max_length=50, verbose_name='操作用户'),
        ),
    ]
