# Generated by Django 4.2.2 on 2023-09-13 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operationHistory', '0003_pmsoperationlogs_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pmsoperationlogs',
            name='file_name',
            field=models.CharField(default='', max_length=50, verbose_name='文件名称'),
        ),
    ]
