# Generated by Django 4.2.2 on 2023-09-13 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operationHistory', '0004_pmsoperationlogs_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pmsoperationlogs',
            name='timestamp',
            field=models.CharField(default='', max_length=50, verbose_name='操作时间'),
        ),
    ]
